### PR TITLE
Variable definitions for windows build

### PR DESCRIPTION
**Pull request by rvuga**
Hi, sorry it took me long to test the merge. A minor thing was missed in devOpcUa.c aind drvOpcUa.cpp. Namely the variables need to be declared before definitions for VC to swallow it, and the counter used for UaVariant needs to be OpcUa type as well.

You can ignore changes to Makefile and st.cmd, I needed that because I am testing with UA demo server.

### CODE REVIEW

**Comment by ralphlange** [comment]
Please be careful.
Moving the `read()` call outside of the semaphore-guarded section possibly introduces a change in behaviour, with race conditions, hang-up situations etc. This does *not* look like a "minor thing" at first glance.

**Comment by rvuga** [comment]
You are right, I wasn't paying attention. Please see the update.

**Comment by rvuga** [comment]
Note that there is another case of read() being outside the lock at line 330, which was not done by me so I left it alone.

**Comment by bkuner** [comment]
Ok, I've merged it and just a bunch of fixes improvements etc also. Before I publish it I realized that my new stuff that use std::regexp is part of c11 and not available of our production machines. So my question to rvuga, what compiler do you use? And what alternative is available on windows. The first choice is boost::regex or if that doesn't work on windows maybe c posix regexp.
To me it is my last day before easter, so have a good easter and I'm lokoing forward to Your answer at 18.4.

**Comment by ralphlange** [comment]
Can you share your improvements for review before merging?

**Comment by rvuga** [comment]
Hi, we use VS2010, so c++11 features are mostly not implemented. Boost is fine, though.

I agree as well, if you commit your changes then I can test and see.

**Pull request merged**
