### PR TITLE
Add mechanism for *.local overrides; .gitignore those files (fixes #8)

### LINKED ISSUE #8: Module should use the *.local override mechanism
Recent EPICS modules use a mechanism based on *.local configuration files (`RELEASE.local` and `CONFIG_SITE.local`) in different locations to override definitions in `RELEASE` and `CONFIG_SITE`. This has two main advantages:

1. *.local files can (and should) be kept outside the version control. Every instance (every developer) can use a different configuration without modifying the files under version control.
2. Override files "over the TOP" (i.e. in `TOP/..`) can control configuration of all underlying modules from a single place.

### PR DESCRIPTION
**Pull request by ralphlange**
Add the necessary includes to the build system files to use *.local overrides for `RELEASE` and `CONFIG_SITE`.

### CODE REVIEW

**Comment by ralphlange** [comment]
After applying this commit, you will have to create two *.local files:

`CONFIG_SITE.local` (probably in `OPCUA/configure`), setting the SDK location
```
UASDK = $(TOP)/../../uasdkcppclient-src-debian7.7-x86_64-gcc4.7.2-v1.5.3-346/sdk
```

`RELEASE.local`, either in `OPCUA/configure` (for this TOP) or in `OPCUA/..` (for all TOPs below), to set the EPICS location
```
EPICS_BASE=$(TOP)/../../BASE
```

**Comment by bkuner** [comment]
Hi Ralph,
the local  .local files are a very good idea, but - it seams to me a little overengenered. As I suffer here at BESSY from to much automagic I'd like to keep it simple. Means just local .local files in each TOP.

So I want to reject this pull request and pull a simplified version.

See also the updated README - known bugs!

**Comment by ralphlange** [comment]
The names and locations have been agreed upon between developers of EPICS Base, areaDetector, and most synApps modules. (Admittedly, synApps is behind in getting the changes into their release.)

What I was proposing is the de-facto standard. Let's please do this as streamlined as possible, and not introduce yet another "simplified" version that introduces confusion and incompatibility, and makes things more complicated in the end.

**Comment by ralphlange** [comment]
And there's no magic involved.
All configuration is kept in human readable files in your local workspace.
No external tools or scripts are used or needed.

**Pull request closed without merging**
